apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-beat-deployment
  labels:
    app: celery-beat

spec:
  replicas: 1

  selector:
    matchLabels:
      app: celery-beat

  template:
    metadata:
      labels:
        app: celery-beat

    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: role
                    operator: In
                    values:
                      - worker

      containers:
        - name: celery-beat

          image: backend-image
          imagePullPolicy: Always

          command:
            - celery
            - -A
            - src.core
            - beat
            - -l
            - info
            - --scheduler
            - django_celery_beat.schedulers:DatabaseScheduler

          envFrom:
            - secretRef:
                name: backend-secrets

            - secretRef:
                name: postgres-secret
          
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"

            limits:
              memory: "128Mi"
              cpu: "200m"
