apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker-deployment
  labels:
    app: celery-worker

spec:
  replicas: 1

  selector:
    matchLabels:
      app: celery-worker

  template:
    metadata:
      labels:
        app: celery-worker

    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: role
                    operator: In
                    values:
                      - worker

      containers:
        - name: celery-worker

          image: backend-image
          imagePullPolicy: Always
  
          command:
            - celery
            - -A
            - src.core
            - worker
            - -l
            - info
            - --concurrency=1

          envFrom:
            - secretRef:
                name: backend-secrets

            - secretRef:
                name: postgres-secret
          
          affinity:
            nodeAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 100
                  preference:
                    matchExpressions:
                      - key: role
                        operator: In
                        values:
                          - infra

          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"

            limits:
              memory: "512Mi"
              cpu: "500m"

