apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: lms




# - postgres/secrets.yml
# - postgres/service.yml
# - postgres/pvc.yml
# - postgres/statefulset.yml
resources:
- redis/deployment.yml
- redis/service.yml
- backend/secrets.yml
- backend/deployment.yml
- backend/service.yml
- backend/ingress.yml
- celery/worker-deployment.yml
- celery/beat-deployment.yml

images:
- name: backend-image
  newName: ghcr.io/learnovax/backend
  newTag: 82397afee06d906671ba58ea352f15c2456adeee
