apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - postgres/secret.yml
  - postgres/service.yml
  - postgres/pvc.yaml
  - postgres/statefulset.yml

  - redis/deployment.yml
  - redis/service.yml

  - backend/secret.yml
  - backend/deployment.yml
  - backend/service.yml

  - celery/worker-deployment.yml
  - celery/beat-deployment.yml
