apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: lms




# - postgres/secrets.yml
# - postgres/service.yml
# - postgres/pvc.yml
# - postgres/statefulset.yml
resources:
- redis/deployment.yml
- redis/service.yml
- backend/secrets.yml
- backend/deployment.yml
- backend/service.yml
- backend/ingress.yml
- celery/worker-deployment.yml
- celery/beat-deployment.yml

images:
- name: backend-image
  newName: ghcr.io/learnovax/backend
  newTag: d11e94768ad013b2304c51a6e5fb3b35dd878cd3
