apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: lms-backend-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.priority: "100"
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure

spec:
  ingressClassName: traefik

  rules:
    - host: website-project.uz
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: lms-backend-service
                port:
                  number: 80

          - path: /static
            pathType: Prefix
            backend:
              service:
                name: lms-backend-service
                port:
                  number: 80
