apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: lms-backend-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.priority: "100"
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure

spec:
  ingressClassName: traefik

  tls:
    - hosts:
        - website-project.uz
      secretName: website-project-tls

  rules:
    - host: website-project.uz
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: lms-backend-service
                port:
                  number: 80

          - path: /static
            pathType: Prefix
            backend:
              service:
                name: lms-backend-service
                port:
                  number: 80
                  
          - path: /ws
              pathType: Prefix
              backend:
                service:
                  name: lms-backend-service
                  port:
                    number: 80
