apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  labels:
    app: backend
type: Opaque
stringData:
  DJANGO_ENV: "prod"
  SECRET_KEY: "test"
  DEBUG: "False"
  CORS_ALLOWED_ORIGINS: "http://localhost:3000,http://localhost:5173,https://website-project.uz"
  REDIS_HOST: "localhost"
  REDIS_PORT: "6379"
  EMAIL_BACKEND: "django.core.mail.backends.smtp.EmailBackend"
  EMAIL_HOST: "smtp.gmail.com"
  EMAIL_PORT: "587"
  EMAIL_USE_TLS: "True"
  EMAIL_HOST_USER: ""
  EMAIL_HOST_PASSWORD: ""
  FRONTEND_URL: "http://localhost:5173"
  #FRONTEND_URL: "https://website-project.uz"
  DOMAIN_URL: "https://website-project.uz"
  ENROL_LINK_URL: "https://website-project.uz/api/course/groups/enroll/"
  USE_S3: "False"
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
  AWS_STORAGE_BUCKET_NAME: ""
  AWS_S3_REGION_NAME: ""
