apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: lms-frontend-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure

spec:
  ingressClassName: traefik

  tls:
    - hosts:
        - website-project.uz
      secretName: website-project-tls

  rules:
    - host: website-project.uz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
