apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: lms

resources:
- secrets.yml
- deployment.yml
- service.yml
- ingress.yml

images:
- name: frontend-image
  newName: ghcr.io/learnovax/frontend
  newTag: f12e22f44b17ee6844118f935692c8ad4a259860
