apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: lms

resources:
- secrets.yml
- deployment.yml
- service.yml
- ingress.yml

images:
- name: frontend-image
  newName: ghcr.io/learnovax/frontend
  newTag: 97c5dc8da94d36e9b6a2a028c277dce63c42d3dd
