apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: lms

resources:
- secrets.yml
- deployment.yml
- service.yml

images:
- name: frontend-image
  newName: ghcr.io/learnovax/frontend
  newTag: f3fd6b5604b6737296ee5bcd64dd49e3da203e86
