name: Backend Infrastructure Pipeline

on:
  push:
    branches:
      - main

    paths:
      - 'backend/**'
    
    workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Render kustomize locally (no cluster access)
      - name: Render manifests (kustomize)
        run: |
          kubectl kustomize backend/prod > /tmp/manifests.yaml

      - name: Install kubeconform
        run: |
          curl -sSL https://github.com/yannh/kubeconform/releases/latest/download/kubeconform-linux-amd64.tar.gz \
            | tar -xz -C /usr/local/bin kubeconform
          kubeconform -v

      - name: Validate manifests (kubeconform)
        run: |
          # -strict: catch missing required fields
          # -ignore-missing-schemas: don’t fail on CRDs/custom resources unless you provide schemas for them
          kubeconform -strict -ignore-missing-schemas -summary /tmp/manifests.yaml


  deploy:
    needs: validate

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup kubectl
        uses: azure/setup-kubectl@v4

      - name: Configure kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config

      - name: Show diff
        run: |
          kubectl diff -k backend/prod || true

      - name: Deploy backend stack
        run: |
          kubectl apply -k backend/prod

      - name: Verify rollout
        run: |
          kubectl rollout status deployment/lms-backend-deployment -n lms --timeout=120s